### PR TITLE
Master Project - DepthMap & co.

### PR DESCRIPTION
**Pull request by Skgland**

### CODE REVIEW

**Comment by Skgland** [comment]
@NiklasRentzCAU ready for review

**Review by NiklasRentzCAU — CHANGES_REQUESTED** [review]
After a quick glance over the changed files and what you did in this PR, I would like this PR to be split for easier reviewing. One PR only affecting the changes required for the project at hand, which I will review. The other PR then with what seems to be style changes/removal of warnings and similar.
For this second PR I already have some comments after checking out the branch locally:
- Code from kieler.klighd.krendering is auto-generated from its corresponding .ecore model in its models/ folder and should not be modified manually. If there are warnings, generating it with a newer generator may fix those, but has no real priority to be updated.
- The code should still be compatible with Java 8, but there are several incompatible changes using the Java 'var' keyword which are not usable in Java 8.
- It would be nice if you would explain the changes you made, were there deprecations that you took care of? Some changes seem to modify totally fine and working code.
For this second PR I would then also invite the other project holder to review the changes.

**Comment by Skgland** [comment]
> After a quick glance over the changed files and what you did in this PR, I would like this PR to be split for easier reviewing. One PR only affecting the changes required for the project at hand, which I will review. The other PR then with what seems to be style changes/removal of warnings and similar.
> For this second PR I already have some comments after checking out the branch locally:
> 
> * Code from kieler.klighd.krendering is auto-generated from its corresponding .ecore model in its models/ folder and should not be modified manually. If there are warnings, generating it with a newer generator may fix those, but has no real priority to be updated.
> * The code should still be compatible with Java 8, but there are several incompatible changes using the Java 'var' keyword which are not usable in Java 8.
> * It would be nice if you would explain the changes you made, were there deprecations that you took care of? Some changes seem to modify totally fine and working code.
>   For this second PR I would then also invite the other project holder to review the changes.

@NiklasRentzCAU The cleanup has now been moved to PR #91 and this now only contains the changes required for the project.

**Review by NiklasRentzCAU — CHANGES_REQUESTED** [review]
These changes alter the KGraph x/y positions for later mapping to Sprotty's SGraph structure correctly, as that does not know about KGraph's insets.
You modify the KGraphElements directly, whereas the positions are correct in the KGraph sense and should not be modified. This could have effects somewhere else if some action wants to know the (KGraph-specific) positions of nodes or similar. The logic applied to the KGraph directly here should be moved and applied to the SGraph while mapping ELK's layout on the KGraph to the SGraph in the `KGraphMappingUtil` class.

**Comment by Skgland** [comment]
> These changes alter the KGraph x/y positions for later mapping to Sprotty's SGraph structure correctly, as that does not know about KGraph's insets.
> You modify the KGraphElements directly, whereas the positions are correct in the KGraph sense and should not be modified. This could have effects somewhere else if some action wants to know the (KGraph-specific) positions of nodes or similar. The logic applied to the KGraph directly here should be moved and applied to the SGraph while mapping ELK's layout on the KGraph to the SGraph in the `KGraphMappingUtil` class.

I have now moved the adjustment logic to the `KGraphMappingUtil`. 
With that change the arrows at the end of lines no longer appear to have the insets applied, so that currently still needs fixing

**Comment by Skgland** [comment]
> > These changes alter the KGraph x/y positions for later mapping to Sprotty's SGraph structure correctly, as that does not know about KGraph's insets.
> > You modify the KGraphElements directly, whereas the positions are correct in the KGraph sense and should not be modified. This could have effects somewhere else if some action wants to know the (KGraph-specific) positions of nodes or similar. The logic applied to the KGraph directly here should be moved and applied to the SGraph while mapping ELK's layout on the KGraph to the SGraph in the `KGraphMappingUtil` class.
> 
> I have now moved the adjustment logic to the `KGraphMappingUtil`.
> With that change the arrows at the end of lines no longer appear to have the insets applied, so that currently still needs fixing

This should now be fixed

**Review by NiklasRentzCAU — APPROVED** [review]
LGTM

**Pull request merged**
