### PR TITLE
Changed SVG generation of KTexts

### PR DESCRIPTION
**Pull request by sailingKieler**
Hey guys, please test the SVG generation with your applications, if possible, and let me know if you see any problems.

### CODE REVIEW

**Comment by sailingKieler** [comment]
See also #44

**Comment by NiklasRentzCAU** [comment]
Generally looks good and now similar to the result that the Klighd-Sprotty view generates. There are still two minor problems I found:
1. The new checkbox for saving the graph as an image is not fully contained in the wizard.
Screenshot from 2020-07-17 08-30-24
2. Either the text size estimation does not include leading or trailing white space characters or the internal SVG Viewer of Eclipse  does something wrong with that:
Screenshot from 2020-07-17 08-42-14-2
This shows that the text spans only the area it should, but the trailing space that is in the texts "input bool " and "output bool " seems to be ignored. However, when viewing the same SVG in Inkscape this problem does not occur. In my code I found this line in the text rendering:
`...{ 'xml:space': 'preserve' } // This attribute makes the text size estimation include any trailing white spaces.`
So adding the attribute xml:space="preserve" here also might improve the overall spacing.

**Comment by sailingKieler** [comment]
@NiklasRentzCAU and @uruuru thanks for the feedback, I'll take care about it on occasion.

**Comment by sailingKieler** [comment]
Reported issues should be fixed now.
@NiklasRentzCAU I would appreciate if you could test the dialog as well as the SVG export with labels containing whitespace.
Thanks!

**Comment by sailingKieler** [comment]
@NiklasRentzCAU or @soerendomroes please merge these changes before preparing the next release.
I'm off this week and rather busy next week, so I won't have time to care. I ask "my customer" about their tests and didn't hear any complaints yet.

**Pull request merged**
