### PR TITLE
Refactor ide independent stuff into an ide plugin

### PR DESCRIPTION
**Pull request by soerendomroes**

### CODE REVIEW

**Comment by sailingKieler** [comment]
The new plugin's stuff is only consumed by the `...ui.view` plugin, right?
Is it intended to be used in non-Eclipse-based IDEs? Might make sense to add an derived version of https://github.com/kieler/KLighD/blob/master/plugins/de.cau.cs.kieler.klighd.standalone/src/de/cau/cs/kieler/klighd/standalone/KlighdStandaloneSetup.java, doesn't it?

**Comment by soerendomroes** [comment]
The main idea was to make the syntheses and stuff like the MessageModel available for setups that do not want to consume the ui plugins. I think a `StandaloneSetup` is orthogonal to this issue.
I suggest to add one if the need arises or is there already one @NiklasRentzCAU ?
This refactoring is a first step to do the same for the KIELER semantics bundles.

**Comment by NiklasRentzCAU** [comment]
Also looks good to me.
There is no derived version of the standalone setup yet, I don't see that we need one anyway. The language server setup in the keith branch will need that, but is not fully implemented over there yet. If we see something that needs to be added to the ide plugin, we'll do it then.

**Comment by soerendomroes** [comment]
The PR build seems to be successful now.

**Comment by soerendomroes** [comment]
I suggest to also include the syntheses in graphs klighd in the ide plugin since they should also not be Eclipse dependent.

**Comment by uruuru** [comment]
@NiklasRentzCAU I guess you refer to github actions. Have a look at this config, should only require small adjustemts: https://github.com/eclipse/elk/blob/master/.github/workflows/ci.yml

**Pull request merged**
