### PR TITLE
klighd +.piccolo: minor improvements & bug fixes here and there

### PR DESCRIPTION
**Pull request by sailingKieler**
Hey guys,

FYI: this PR contributes some useful refinements and a bugfix in the magnifier lens handling.
Should be harmless ;-).

### CODE REVIEW

**Review by NiklasRentzCAU — APPROVED** [review]
LGTM. I don't even know if this magnifying lens is used anywhere for us so I cannot evaluate that change, but the remaining fixes seem fine.

**Review by a-sr — APPROVED** [review]
Looks ok

**Comment by sailingKieler** [comment]
> LGTM. I don't even know if this magnifying lens is used anywhere for us so I cannot evaluate that change, but the remaining fixes seem fine.

Oh you can. In an Eclipse-based diagram editor / view just press alt+ctrl/cmd
(the diagram widget must have focus, which is sometimes a bit cumbersome when the zoom buttons are visible - they often catch the focus immediately)

**Review by soerendomroes — APPROVED** [review]
Looks good to me

**Pull request merged**
